### ISSUE TITLE
Extending CmsContentPages model

### ISSUE THREAD

**Issue by howdu** [phpsa/filament-cms#2]
Loving this thank you! Just wondering if there was a way of adding custom pages? I've got some extra fields needed in the sidebar currenting overwirting generateFormSidebar. Is this the best way?

**Comment by phpsa** [comment]
Best way would be to either add a new card under 
```
public static function sidebarCards(): array
    {
        return [
            FeaturedImageSection::make('featured_image'),
        ];
    }
  ```
  
  Or use customMeta to add to the initial sidebar
  
  ```
  public static function customMeta(): array
    {
        return [
            FeaturedImageSection::make('featured_image'),
        ];
    }
